# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Mapp" do
pod 'AFNetworking'
pod 'Canvas'
pod 'Mapbox-iOS-SDK'
pod 'MDCSwipeToChoose'
pod 'JSONModel'
pod 'SDWebImage'
end

target "MappTests" do

end

